object NotificationCommand "notify-alertmanager-host" {
  import "plugin-notification-command"
  command = [ SysconfDir + "/icinga2/scripts/notify-alertmanager.sh" ]
  arguments = {
    "-t" = "host"
    "-T" = "$notification.type$"
    "-H" = "$host.name$"
    "-d" = "$host.display_name$"
    "-A" = "$host.address$"
    "-s" = "$host.state$"
    "-u" = "$alertmanager_url$"
    "-i" = "$icingaweb2url$"
    "-c" = "$notification.comment$"
    "-a" = "$notification.author$"
    "-l" = "$alertmanager_labels$"
  }
}

object NotificationCommand "notify-alertmanager-service" {
  import "plugin-notification-command"
  command = [ SysconfDir + "/icinga2/scripts/notify-alertmanager.sh" ]
  arguments = {
    "-t" = "service"
    "-T" = "$notification.type$"
    "-H" = "$host.name$"
    "-d" = "$host.display_name$"
    "-A" = "$host.address$"
    "-s" = "$service.state$"
    "-n" = "$service.name$"
    "-N" = "$service.display_name$"
    "-u" = "$alertmanager_url$"
    "-i" = "$icingaweb2url$"
    "-c" = "$notification.comment$"
    "-a" = "$notification.author$"
    "-l" = "$alertmanager_labels$"
  }
}

object User "alertmanager" {
  display_name = "Alertmanager"
  groups = [ "icingaadmins" ]
  states = [ OK, Warning, Critical, Unknown, Up, Down ]
  types = [ Problem, Recovery, Acknowledgement ]

  vars.alertmanager_url = "http://alertmanager:9093"
  vars.icingaweb2url = "http://icinga.example.com/icingaweb2"
  vars.alertmanager_labels = "severity=warning"
}

apply Notification "alertmanager-host" to Host {
  command = "notify-alertmanager-host"
  users = [ "alertmanager" ]
  assign where host.vars.notify_alertmanager == true
}

apply Notification "alertmanager-service" to Service {
  command = "notify-alertmanager-service"
  users = [ "alertmanager" ]
  assign where service.vars.notify_alertmanager == true
}

object Host "example-host" {
  import "generic-host"
  address = "127.0.0.1"
  address6 = "::1"
  vars.notify_alertmanager = true
}